midware: ros2
# midware: cyber

workspace: '/home/ros/ros2proj/ComP_demo/ComP_demo_ws'
data_path: '/home/ros/ros2proj/ComP_demo/ComP_demo_ws/src/comp_topic_rclcpp/data/camera'
log_path: '/home/ros/ros2proj/ComP_demo/ComP_demo_ws/src/comp_topic_rclcpp/logs'
output_path: '/home/ros/ros2proj/ComP_demo/ComP_demo_ws/src/comp_topic_rclcpp/output'
model_path: '/home/ros/ros2proj/ComP_demo/ComP_demo_ws/src/comp_topic_rclcpp/resources/yolov5s.onnx'
